-- AlterTable
ALTER TABLE `projects` ADD COLUMN `subtotal` DECIMAL(14, 2) NOT NULL DEFAULT 0,
    ADD COLUMN `taxAmount` DECIMAL(14, 2) NOT NULL DEFAULT 0,
    ADD COLUMN `taxRate` DECIMAL(5, 2) NOT NULL DEFAULT 0;
